services:

  db:
    image: postgres:15
    container_name: market_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: market_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  market:
    image: market_app
    build:
      context: .
    container_name: market_app
    env_file:
      - .env-non-dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "cd src && alembic upgrade head && cd .. && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000

  celery:
    image: market_celery
    build:
      context: .
    container_name: market_celery
    command: sh -c "celery -A app.tasks.celery_app worker -l INFO"
    env_file:
      - .env-non-dev
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - C_FORCE_ROOT=1  # Разрешает запуск от root

  celery_beat:
    image: market_celery_beat
    build:
      context: .
    container_name: market_celery_beat
    command: sh -c "celery -A app.tasks.celery_app beat -l INFO"
    env_file:
      - .env-non-dev
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - C_FORCE_ROOT=1  # Разрешает запуск от root

volumes:
  postgresdata:
